---
title: "Advanced topics (`C` interface)"
author: "Virgilio Gómez Rubio"
date : ""
output:
  ioslides_presentation:
    incremental: false
    self-included: true
    css: styles.css
    #logo: uclm.jpg
---


## Introduction

* `R` is a flexible programming language

* `R` is an interpreted language

* Some tasks can be written in faster languages (such as `C` or `Fortran`)

* We may want to use some external libraries from `R` (e.g., LAPACK or BLAS).

* `R` provides a number of ways to link to external code and libreries

## Calling 'foreign languages' from R {.smaller}

In general, calling foreign code from `R` involves:

1. Placing source code in the appropriate directory (often under `mypkg/src`).

2. Writing wrapper `R` functions (under `mypkg/R`) to call the foreign functions.

3. Setting up a compiling environment (this can be tricky...):

    * Install compilers.

    * Install external libraries.

    * Set up compiling options (often via `configure` and `make`).

4. Building a binary version of the package with a compiled library with the foreign code (this can be VERY tricky sometimes...).



## Required tools

* `C`/`Fortran`/`...` compilers

* LaTeX

* Possibly, other external libraries: BLAS, LAPACK, MPI, etc.

* ...

## Required tools

**Windows**

Install R tools from:

 [https://cran.r-project.org/bin/windows/Rtools/](https://cran.r-project.org/bin/windows/Rtools/)

**Mac OS X**


Tools for building `R` on Mac OS X are available here:

[https://cran.r-project.org/bin/macosx/tools/](https://cran.r-project.org/bin/macosx/tools/)

**Linux**

Install the '-dev' version of `R` and associated packages.






## `C` interface


* `.C` function

    * Uses simple `C` data types as arguments.

    * Results are returned in one (o several of the arguments).


* `.Call` function

    * Uses 'complex `SEXP` data structures as arguments.

    * Results are returned by the function (as a `SEXP`).

* Make sure to register your functions!! (see below)

## `.C` interface (`C` code)

File `sumR/src/sumC.c`.

```
void sumC(double *x, double *y, double *res) {
  res[0] = x[0] + y[0];
}
```

## `.C` interface (`R` code) 

File `sumR/R/sumRC.R`.

```
#' @name sumRC
#' @rdname sumR
#'
#' @examples
#' sumRC(1, 2)
#'
#' @details \code{sumRC} is an implementation using the \code{.C} interface.
#'
#' @export
#'
#' @useDynLib sumR sumC
sumRC <- function(x, y) {
 res <- .C("sumC", as.double(x) , as.double(y), double(1), PACKAGE = "sumR")

 return(res[[3]])
}
```


## `.Call` interface (`C` code)

File `sumR/src/sumCall.c`

```
#include <stdio.h>
#include <R.h>
#include <Rinternals.h>

SEXP sumCall(SEXP sexp_x, SEXP sexp_y) {
  double x = asReal(sexp_x);
  double y = asReal(sexp_y);

  double res;

  res = x + y;

  return ScalarReal(res);
}
```

## `.Call` interface (`R` code)

File `sumR/src/sumRCall.R`

```
#' @name sumRCall
#' @rdname sumR
#'
#' @examples
#' sumRCall(1, 2)
#'
#' @details \code{sumRCall} is an implementation using the \code{.Call} interface.
#'
#' @export
#'
#' @useDynLib sumR sumCall
sumRCall <- function(x, y) {
  res <- .Call("sumCall", x , y)

  return(res)
}
```

## Header file 

The defintion of the functions are defined in `sumR/src/sumR.h`.

```
#include <R.h>
#include <Rinternals.h>

void sumC(double *x, double *y, double *res);
SEXP sumCall(SEXP sexp_x, SEXP sexp_y);
```

## How to register your functions

* It is convenient to 'register' `C` functions to called by `.C` or `.C`


* Check file `sumR/src/init.c` to see an example on how this is done.

* Functions are listed using *tables* `R_CMethodDef` (`.C`) or 
`R_CallMethodDef` (`.Call`).

* An initialization function (`R_init_sumR`) is defined to actually
register the functions and make them visible.

## How to register functions {.smaller}

Function `sumR/src/init.c`.

```
/* Based on spdep/serc/init.c by Roger S. Bivand*/

#include "sumR.h"
#include <Rinternals.h>
#include <R_ext/Rdynload.h>

static const R_CMethodDef CEntries[]  = {
    {"sumC", (DL_FUNC) &sumC, 3},
    {NULL, NULL, 0}
};

static R_CallMethodDef CallEntries[] = {
    {"sumCall", (DL_FUNC) &sumCall, 2},
    {NULL, NULL, 0}
};


void R_init_sumR(DllInfo *dll)
{
    R_registerRoutines(dll, CEntries, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);

}
```

## `SEXP`  variables 

* A `SEXP` is a pointer to a data structure in memory.

* `SEXP` can be used to access `R` variables and object within `C` code.

* There are function to convert between `SEXP` and  `C` data types:

[http://r-pkgs.had.co.nz/src.html#clang](http://r-pkgs.had.co.nz/src.html#clang). 

# Package development on github

## Github

* Github is a hosting service that provices access to free git repositories.

* git is a distributed version control system.

* git clients for several platforms can be obtained from:

    [https://git-scm.com](https://git-scm.com).

* Main commands:

    * `clone`, to make a local copy of a repository.

    * `commit`, to commit changes (not submitted).

    * `push`, to actually submit a commit.

## Travis CI

* [Travis CI](https://travis-ci.org) is a service for testing and deploying code.

* Essentially, Travis CI can help us to check our R packages hosted on github.

     1. Log in to Travis CI with our github account.

     2. Give Travis CI access to our repository.

     3. Activate checking of our repositories.

* Configuration of Travis CI is done with `mypkg/.travis.yml`

* More info vabout using Travis CI with `R` can be found here:

[https://docs.travis-ci.com/user/languages/r/](https://docs.travis-ci.com/user/languages/r/)


# Tests

## Why testing?

* Testing in import to make sure that a function does what it is expected to do.

* By automating testing we protect against possible bug introduced in the code.

* Tests are useful to make sure that the package works as expected under
different OS's and architectures.

* In a nutshell, tests make our package more robust.



## `test` structure

* Tests are included under `mypkg/tests`.

* Tests can be run with `devtools::test()`.

* In order to set up the directories to use `testthat`package, we can
use `devtools::use_tetthat()`.

* File `mypkg/tests/testthat.R` will run all the tests under `mypkg/tests/testthat` when the package is checked.


## `testhat` package

* Tests are implemented using the `test_that` function:


```
test_that("Test that ...", {

  Include_test_code_here
})
```

* Several tests can be included in several files.

* Each file is run independently of each other.

* Make sure to remove all temporary files, etc. after running the tests.

## Example: package `sumR`  {.smaller}

File `sumR/test/testthat/test_sumR.R`.

```
test_that("Sum of 1 and 2 is 3", {
  expect_equal(sumR(1, 2), 3)
  expect_equal(sumR(2, 1), 3)
})

test_that("sumR returns a single number", {
  expect_equal(length(sumR(1, 1)), 1)
})

test_that("sumR returns a double value", {
  expect_type(sumR(1, 1), "double")
})

test_that("Example of skipped test", {
  skip("I wil skip this test")
  expect_type(sumR(1, 1), "integer")

})
```


## Some considerations about testing


* Beware of different local configurations of the host machine (Windows,
Mac, Linux, R version, installed packages, etc.).

* If needed, tests can be skipped:

    * `skip("Text")`, to skip tests in general.

    * `skip_on_cran()`, to skip test when the package in built on CRAN

* `skip` can be used BEFORE the actual tests occur.

* Skipped tests are displayed with an `S`.


## Example: package `sumR`  {.smaller}

File `sumR/test/testthat/test_sumR.R`.

```
test_that("Sum of 1 and 2 is 3", {
  expect_equal(sumR(1, 2), 3)
  expect_equal(sumR(2, 1), 3)
})

test_that("sumR returns a single number", {
  expect_equal(length(sumR(1, 1)), 1)
})

test_that("sumR returns a double value", {
  expect_type(sumR(1, 1), "double")
})

test_that("Example of skipped test", {
  skip("I wil skip this test")
  expect_type(sumR(1, 1), "integer")

})
```

